### ISSUE TITLE
Curator -> moderator -> coordinator!

### ISSUE THREAD

**Issue by ibartomeus** [ibartomeus/traitbase#14]
Should we change the name of curators, to moderators? We don't want the responsibility of ensuring data is perfect, we just catalyze the process. Any other name that reflects that role?

**Comment by indradecastro** [comment]
catalyzers?
facilitators?
coordinators? goes well with "bee traits coordinator", "parasitoid 
traits coordinator"...
administrator? sounds too techy?

**Comment by ibartomeus** [comment]
I like coordinator!

**Comment by liamkendall** [comment]
I like coordinator too!

**Comment by eapm** [comment]
Agree with coordinator! And, the invite now worked ;)

**Comment by ibartomeus** [comment]
Fixed in the webpage. Will be updated in the next PR.
