### ISSUE TITLE
**small package issues**

### ISSUE THREAD

**Issue by ibartomeus** [ibartomeus/traitbase#19]
[X] load taxize with package
    [X] `parseErrors` paradoxialy gives an error when there are no errors (Nacho will fix this)
    [X] Add to `privateImport` an if statement to show a 404 error or the 505 when this occurs.
    [x] cleanSpecies gives error -> Nacho (Update from elsewhere with verbose = TRUE)
    [X] Modify ParseError to target unrecognized or ambigous species for you (Nacho)

**Comment by eapm** [comment]
Does loading taxize = working to access non ITIS sources? (for the wish list :))

**Comment by KevCaz** [comment]
In the upcoming PR: 
- [X] load taxize with package

**Comment by KevCaz** [comment]
see https://github.com/metadevpro/traitbaser/pull/7

**Comment by KevCaz** [comment]
When I retrieve the data base, all entries but a few have 12 columns, the few other have 11. Is that normal?  

```R
R> names(responseNA[[1]])
 [1] "_links"      "_id"         "species"     "order"       "superfamily" "family"      "subfamily"   "tribe"       "genus"


[10] "subgenus"    "__v"         "_createdAt"
R> names(responseNA[[19699]])
 [1] "_links"      "_id"         "genus"       "species"     "order"       "superfamily" "family"      "tribe"       "subgenu
s"
[10] "__v"         "_createdAt"
# subfamily missing
R> table(val)
val
   11    12
  344 19387
```

Regarding the `to_dataframe()` function, I think what we should do is: ensure all columns exist, sort all elements of the list and then use a `do.call(rbind, list)`, that will be the output and if the user wants to remove metadata, it's up to him! Also, I think this function should also be part of `auxiliar.R`.

And I will remove the `_links` column and create a function that parse it. I cannot see how users can use it, but it may be useful for the development of the package.

**Comment by ibartomeus** [comment]
parseErrors paradoxialy gives an error when there are no errors (Nacho will fix this)
FIXED.

**Comment by ibartomeus** [comment]
[] Modify ParseError to target unrecognized or ambigous species for you (Nacho)
FIXED

**Comment by ibartomeus** [comment]
All fixed
