### ISSUE TITLE
species-level trait data

### ISSUE THREAD

**Issue by liamkendall** [ibartomeus/traitbase#23]
I know @KevCaz has apt reservations about using species-level trait information but I've been thinking about this and think we limit ourselves quite a lot if we do only allow uploads of intraspecific trait information. Especially as some traits are static at the species-level.

e.g. see supp material from this paper which only provides species-level trait data but has comprehensive literature list of how they obtained trait values
https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0205854

**Comment by KevCaz** [comment]
I guess you're mistaking me for someone else as I has never said that :smile: !

**Comment by liamkendall** [comment]
@KevCaz sorry! Must've misunderstood during our skype conversation but still a valid point to have as intraspecific variation is very important

**Comment by liamkendall** [comment]
I realise it was @indradecastro so ive added him to the conversation :)

**Comment by ibartomeus** [comment]
Liam, 

We are not limiting our selves. Just enter this data as a single individual information. Coarse traits like sociality will appear in different publications. If a species is always social, 100% of the sociality trait will be "social". And you have a robust species-level trait. This is important for cases were different publications disagree in the species level trait or miss-categorized a species. In those cases, you can track where this comes from and what do you trust. If you create a species level trait. This needs to be unique and you need to make sure it is right, this is not feasible. 

So, just enter this dataset as one more observation.
