### ISSUE TITLE
Website not available

### ISSUE THREAD

**Issue by KevCaz** [ibartomeus/traitbase#24]
Since yesterday, the website is not available, is that normal?

I think it'd be nice to have a badge that shows whether the the website is on or off. Could be useful for maintenance purposes!

**Comment by pjmolina** [comment]
I am investigating it. Looks like a DNS issue.

**Comment by KevCaz** [comment]
Thanks @pjmolina !

**Comment by pjmolina** [comment]
Can you check if works now for you?
The DNS provided did something nasty with the DNS.
It should be fixed now. I will open an issue there.

**Comment by ibartomeus** [comment]
It works for me now, Thanks Pedro! You are fast!

**Comment by KevCaz** [comment]
Yeah :fireworks: thanks Pedro!
